version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=messenger-api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./db://var/lib/postgresql:z